[0;34m[INFO][0m Генерируем тесты для src/shared/ui/redesigned/Test Component/TestComponent5 copy 2.tsx...
[0;34m[INFO][0m Попытка использовать Hugging Face Router API...
[0;34m[INFO][0m Используем авторизованный запрос к Hugging Face Router API
[1;33m[WARN][0m Router API недоступен или вернул ошибку
[0;31m[ERROR][0m Ответ API: {"id":"chatcmpl-534017eb-2e62-4087-b3e2-137a4a0ea67f","choices":[{"finish_reason":"length","index":0,"message":{"content":"<think>
Okay, I need to create comprehensive unit tests for the TestComponentZ React component using Jest and React Testing Library. Let me start by understanding the component's structure and props.

First, the component is a memoized functional component. It takes several props like title, text, variant, align, size, bold, and data-testid. The component uses classNames utility to combine classes, and it maps size to header tags and classes. The rendered output includes a div wrapping either a header (h1, h2, h3) for the title and/or a paragraph for the text, with various classes applied based on props.

Now, I need to test different scenarios. Let's outline the test cases:

1. **Renders with title and text**: Check if both title and text are rendered correctly.
2. **Renders only title**: When text is not provided.
3. **Renders only text**: When title is not provided.
4. **Applies correct variant classes**: primary, accent, error.
5. **Applies correct align classes**: left, center, right.
6. **Applies correct size classes and header tags**: For each size, check the class and the header tag (h1, h2, h3).
7. **Bold class is applied when bold is true**.
8. **Custom className is applied**.
9. **Data-testid attributes are correctly set**.
10. **Memoization check**: Ensure the component is wrapped with React.memo and does not re-render when props are the same.

For each test case, I'll use React Testing Library to render the component and query the DOM elements. I'll use data-testid attributes to target elements, check text content, classes, and element types.

Let me start writing the tests. I'll need to import the component and the necessary utilities. Also, since the component uses classNames, I might need to mock it if it's not already a mock. But since the user provided the code, maybe it's better to use the actual implementation. However, the classNames function is imported from another module, so I need to ensure that the test can access it. But since the component uses it, the tests will rely on the actual class names being applied.

Wait, the component uses cls from './Text.module.scss'. Since it's a CSS module, the class names are imported as variables. But in the test, I can't directly access those unless I mock the module. However, for the purpose of testing class application, maybe I can check the presence of classes based on the props. For example, if variant is 'accent', the component should have the cls.accent class. But since cls is not accessible in the test, perhaps I need to mock the module. Alternatively, maybe the test can just check if the classes are applied based on the props, assuming that the classNames function is working correctly.

But the user's code uses the classNames utility, which combines the base class (cls.Text), modifiers (like cls.bold if bold is true), and additional classes (variant, align, size). So, for example, if variant is 'accent', the additional class would include cls.accent. So in the test, I can check if the element has the class 'accent' (assuming that the cls.accent is the correct class name). However, without knowing the actual class names from the CSS module, this might be tricky. But perhaps the test can just check for the presence of the class names as they are generated by the classNames function. Alternatively, maybe the test can use data attributes or other means to verify the correct classes are applied.

Alternatively, maybe the test can check the className prop of the rendered elements. For example, if the component is rendered with variant 'accent', the root div should have the class 'Text_accent' (assuming that's how the CSS module exports it). But since the actual class names are not known, perhaps the test can't directly check for them. However, the user's code uses the classNames function, which is supposed to handle combining classes. So maybe the test can focus on the logic of the component, like ensuring that the correct classes are passed to classNames based on the props.

But in the test, how can I verify that the correct classes are applied? For example, if the variant is 'accent', the additional array includes cls[variant], which would be cls.accent. So the test can check if the root element has a class that includes 'accent' (assuming that the CSS module's cls.accent is a unique class name). However, without knowing the exact class names, this is challenging. Maybe the test can use the data-testid to get the element and check if the className includes the expected variant.

Alternatively, perhaps the test can use the 'toHaveClass' matcher. For example, if the component is rendered with variant 'accent', the root element should have the class 'accent' (assuming that the CSS module's cls.accent is 'accent'). But this depends on how the CSS module is set up. Since the user's code uses cls.module.scss, the actual class names might be something like 'Text_accent', but without knowing that, the test can't directly check. Hmm, this is a problem.

Wait, maybe the test can check the presence of the class names by using the classNames utility. For example, if the component is rendered with variant 'accent', the additional classes would include cls.accent. The classNames function combines the base class (cls.Text), modifiers (like cls.bold if bold is true), and the additional classes. So the root element's className would be the result of classNames(cls.Text, { [cls.bold]: bold }, additional). The additional array includes sizeClass, variant class, and align class.

But since the test can't access cls, maybe the test can't directly verify the class names. However, the user's code uses the classNames function, which is supposed to handle combining classes. So perhaps the test can focus on the logic of the component, like ensuring that the correct classes are passed to classNames based on the props. For example, if the variant is 'accent', the additional array includes cls.accent, so the root element should have that class. But without knowing the actual class name, how can the test check that?

This is a bit of a problem. Maybe the test can use the data-testid attributes to target the elements and then check the className. For example, if the component is rendered with variant 'accent', the root element (which has data-testid='Text') should have a className that includes the variant's class. But since the actual class name is not known, perhaps the test can't do that. Alternatively, maybe the test can check if the className includes the variant name. For example, if variant is 'accent', the className should include 'accent' as part of it. But that depends on how the CSS module is structured. If the CSS module exports classes like 'accent', then the test can check for that. If the CSS module uses a different naming convention, like 'Text_accent', then the test would need to check for that.

But since the user hasn't provided the actual CSS module code, I have to assume that the classNames function is working correctly and that the component is applying the correct classes based on the props. Therefore, the test can focus on the","role":"assistant"}}],"created":1748554022,"model":"qwen-3-32b","system_fingerprint":"fp_d7c70c58dd52e0143bae","object":"chat.completion","usage":{"prompt_tokens":544,"completion_tokens":1500,"total_tokens":2044,"prompt_tokens_details":{"cached_tokens":0}},"time_info":{"queue_time":0.00050685,"prompt_time":0.011782273,"completion_time":0.947417122,"total_time":0.9608843326568604,"created":1748554022}}
[0;34m[INFO][0m Создаем базовый шаблон теста...
import React from 'react';
import { render, screen } from '@testing-library/react';
import '@testing-library/jest-dom';
import { TestComponentZ } from './TestComponent5 copy 2';

describe('TestComponentZ', () => {
  it('should render without crashing', () => {
    render(<TestComponentZ />);
    expect(document.body).toBeInTheDocument();
  });

  it('should render with provided props', () => {
    const testProps = {
      className: 'test-class',
      'data-testid': 'test-component'
    };
    
    render(<TestComponentZ {...testProps} />);
    const element = screen.getByTestId('test-component');
    expect(element).toBeInTheDocument();
    expect(element).toHaveClass('test-class');
  });

  // TODO: Add more specific tests based on component functionality
  it('should handle user interactions', () => {
    // Add interaction tests here
    expect(true).toBe(true);
  });
});
