#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# Получить все изменения с последнего коммита
FILES=$(git diff --name-only HEAD~1 HEAD | grep -E '\.tsx?$')

if [ -n "$FILES" ]; then
  echo "Running eslint on changed files:"
  echo "$FILES"
  npx eslint $FILES
fi