#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# Получить все изменения с последнего коммита
FILES=$(git diff --name-only HEAD~1 HEAD | grep -E '\.tsx?$')

if [ -z "$FILES" ]; then
    echo "No changed files... Skipping tests."
    exit 0
fi

if [ -n "$FILES" ]; then
  echo "Running eslint on changed files:"
  echo "$FILES"
  npx eslint $FILES

  echo "Running jest with --findRelatedTests:"
  echo "$FILES" | xargs npx jest --findRelatedTests
fi